### ISSUE TITLE
how i train this?

### ISSUE THREAD

**Issue by ohari5336** [open-dating/adult-image-detector#2]
how I train and teach this for detect perfectly?

**Comment by grinat** [comment]
@ohari5336 all info about used model https://github.com/yahoo/open_nsfw/tree/a4e13931465f4380742545932657eeea0a10aa48

**Comment by ohari5336** [comment]
you mean I found here 

\adult-image-detector\models\open_nsfw\nsfw_model

**Comment by grinat** [comment]
> you mean I found here
> 
> \adult-image-detector\models\open_nsfw\nsfw_model

adult-image-detector\models\open_nsfw\nsfw_model taken from https://github.com/yahoo/open_nsfw/tree/a4e13931465f4380742545932657eeea0a10aa48
